### ISSUE TITLE
`--datadir` doesn't work

### ISSUE THREAD

**Issue by frenzymadness** [fedora-python/portingdb#489]
Hello.

It seems that specifying `--datadir` doesn't work. For example, when I wanted to load a database from the data/ directory, I got the following strange error:

```
$ basename $PWD
portingdb
$ python -m portingdb --datadir data/ load
Traceback (most recent call last):
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: dependencies.run_time

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lbalhar/Dropbox/Projekty/portingdb/portingdb/__main__.py", line 3, in <module>
    main()
  File "/home/lbalhar/Dropbox/Projekty/portingdb/portingdb/cli.py", line 19, in main
    return cli(obj={})
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lbalhar/Dropbox/Projekty/portingdb/portingdb/cli.py", line 127, in load
    warnings = load_from_directories(db, datadirs)
  File "/home/lbalhar/Dropbox/Projekty/portingdb/portingdb/load.py", line 270, in load_from_directories
    key_columns=['requirer_name', 'requirement_name'])
  File "/home/lbalhar/Dropbox/Projekty/portingdb/portingdb/load.py", line 428, in bulk_load
    ignored_columns=ignored_columns))
  File "/home/lbalhar/Dropbox/Projekty/portingdb/portingdb/load.py", line 474, in bulk_load
    existing_rows = list(db.execute(sel))
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1187, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/lbalhar/.virtualenvs/portingdb/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: dependencies.run_time [SQL: 'SELECT dependencies.requirer_name, dependencies.requirement_name, dependencies.id, dependencies.run_time, dependencies.build_time, dependencies.unversioned \nFROM dependencies \nWHERE dependencies.requirer_name IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) AND dependencies.requirement_name IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('abiword', 'asv', 'PyPE', 'PyDrive', 'capstone', 'claws-mail', 'R2spec', 'cherokee', 'bitlyclip', 'blktrace', 'boost', 'alacarte', 'blueproximity', 'cgit', 'assimp', 'Spawning', 'cfv', 'copr-rpmbuild', 'Pyrex', 'calibre', 'atomicapp', 'certmaster', 'audio-convert-mod', 'b43-tools', 'cinnamon', 'ailurus', 'OpenMolcas', 'bro', 'anki', 'catfish', 'PyYAML', 'cherrytree', 'chirp', 'NFStest', 'archivemail', 'comedilib', 'angrydd', 'WALinuxAgent', 'beaker', 'barry', 'copr-frontend', 'bmpanel2', 'bitten', 'calamares', 'bugyou_plugins', 'TeXamator', 'caribou', 'Singular', 'cantor', 'comix', 'configsnap', 'PyPAM', 'cairo-dock-plug-ins', 'bkchem', 'check-mk', 'certbot', 'cashe', 'apitrace', 'cas', 'carbonate', 'cppcheck', 'bugzilla', 'avahi', 'Zim', 'babel', 'bup', 'bluefish', 'PySolFC', 'cloudtoserver', 'cjdns', 'alignak', 'beecrypt', 'bibus', 'centerim', 'autotest-framework', 'PyRTF', 'Ray', 'PyGreSQL', 'PyXB', 'bacula2', 'ceph-deploy', 'avogadro', 'PyQwt', 'clang', 'airinv', 'cmdtest', 'VMDKstream', 'alsa-tools', 'Io-language', 'bodhi', 'captcp', 'brial', 'cobbler', 'belier', 'codemod', 'blueberry', 'ViTables', 'cassandra', 'chm2pdf', 'a2jmidid', 'byobu', 'asciidoc', 'createrepo', 'bpython', 'audit', 'childsplay', 'aubio', 'WebShell', 'bzr', 'RunSnakeRun', 'bitfrost', 'catkin', 'archmage', 'cachedir', 'cmpi-bindings', 'chromium', 'classification-banner', 'autodownloader', 'asymptote', 'GeographicLib', 'autokey', 'condor', 'bakefile', 'Cython', 'batti', 'ahkab', 'cracklib', 'contextkit', 'afflib', 'brotli', 'arandr', 'bleachbit', 'alot', 'airtsp', 'PyMca', 'SoapySDR', 'copr-backend', 'clustershell', 'PyQt4', 'asterisk', 'CheMPS2', 'ccnet', 'autocloud', 'airrac', '389-ds-base', 'cloud-utils', 'cmusphinx3', 'GitPython', 'antlr', 'coq', 'chameleon', 'stdair', 'python-acme', 'python-flask', 'pybluez', 'gpgme', 'python-sphinx_rtd_theme', 'xemacs-packages-extra', 'python-pmw', 'cherokee', 'pyliblzma', 'python-enchant', 'boost', 'python-zope-component', 'python-kitchen', 'kf5-ki18n', 'euca2ools', 'python-ply', 'python-httplib2', 'python-eventlet', 'python-requests', 'libxslt', 'mpich', 'sphinxbase', 'python-cheetah', 'Pyrex', 'python-pyrfc3339', 'python-send2trash', 'gnome-python2-desktop', 'libglade2', 'gtk2', 'python-paramiko', 'python-cssutils', 'python-feedparser', 'GConf2', 'python-docutils', 'python-jsonpointer', 'python-psycopg2', 'python-rpm-macros', 'python-websocket-client', 'python-cherrypy', 'PyYAML', 'python-setuptools', 'python-empy', 'python-cryptography', 'libxml2', 'trac', 'python-coverage-test-runner', 'python-pycurl', 'pyfribidi', 'pytz', 'python-nose', 'python-oasa', 'python-dateutil', 'pyxdg', 'python-urlgrabber', 'python-curtsies', 'tunir', 'python-retask', 'python-fedora', 'pygtksourceview', 'python-click', 'python-ttystatus', 'python-mock', 'python-lxml', 'gnome-doc-utils', 'python-oauth2client', 'python-gitdb', 'fuse-python', 'newt', 'vte', 'pyserial', 'python-urwid', 'mercurial', 'python-iniparse', 'python-redis', 'sip', 'dblatex', 'python-sqlalchemy-utils', 'python-josepy', 'wxPython', 'python-pytest-cov', 'python-mutagen', 'python-cassandra-driver', 'pygtk2', 'python-pillow', 'python-pexpect', 'python-remoto', 'python-parsedatetime', 'python-anymarkup', 'pyOpenSSL', 'python-apsw', 'python-sqlalchemy', 'libappindicator', 'pygame', 'python-zope-interface', 'gnome-python2', 'python-configargparse', 'file', 'python-urwidtrees', 'python-chm', 'python-netaddr', 'libevent', 'pylibacl', 'python-regex', 'epydoc', 'python-unittest2', 'yum', 'python-pep8', 'python-cliapp', 'pygobject3', 'python-prettytable', 'python-six', 'python-simplejson', 'python-BeautifulSoup', 'pycairo', 'python-freezegun', 'python-libpagure', 'python-greenlet', 'PyQwt', 'python-msgpack', 'python-rospkg', 'numpy', 'python-enum34', 'python-dpkt', 'future', 'cmdtest', 'pyaudio', 'python-distutils-extra', 'python-squaremap', 'odfpy', 'python-krbV', 'pyparsing', 'python-repoze-sphinx-autointerface', 'python2-matplotlib', 'pygobject2', 'python-twisted', 'python-setproctitle', 'python-munch', 'libsearpc', 'createrepo', 'rpm', 'rmol', 'python-html5lib', 'python-jedi', 'python-markdown', 'dbus-python', 'notify-python', 'python-netifaces', 'python-alsa', 'python-bitlyapi', 'pytest', 'python-suds', 'sevmgr', 'python-dns', 'python-qt5', 'python-pygments', 'pyxattr', 'python-sphinxcontrib-httpdomain', 'Cython', 'koji', 'python-mako', 'sugar-toolkit-gtk3', 'python-alembic', 'lilypond', 'python-beautifulsoup4', 'yum-metadata-parser', 'python-tables', 'deltarpm', 'python-sphinx', 'python-tornado', 'PyQt4', 'mod_wsgi', 'python-ethtool', 'airrac', 'python-configobj', 'python-html5-parser', 'fedmsg', 'python-mechanize', 'python-watchdog', 'python-markupsafe', 'python-mysql', 'python2', 'google-api-python-client', 'notmuch', 'python-jinja2', 'python-pbr', 'python-psutil', 'openmpi')] (Background on this error at: http://sqlalche.me/e/e3q8)
```
Doing the same in the `data` directory works:
```
$ cd data
$ PYTHONPATH=.. python -m portingdb load
{'bug', 'repo'}
{'bug', 'homepage', 'repo'}
overriding "legacy-leaf" status: fedora: cairo-dock-plug-ins
overriding "legacy-leaf" status: fedora: edk2
```
The same bug exists when a database is ready in data folder:
```
$ basename $PWD
portingdb
$ ls -1 data/portingdb.sqlite 
data/portingdb.sqlite
$ python -m portingdb --datadir data/ status
Database not filled; please run portingdb load
```
And it again works when executed in the data fodler:
```
$ cd data
$ PYTHONPATH=.. python -m portingdb status
 50.0% Upstream  (119 released, 7 idle, 5 dropped, 117 unknown) / 248
 74.4% Fedora  (257 legacy-leaf, 2453 released, 44 mispackaged, 912 idle, 68 dropped) / 3734
```
`serve` command is not affected
```
$ basename $PWD
portingdb
$ PYTHONPATH=. python -m portingdb serve
 * Serving Flask app "portingdb.htmlreport" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

**Comment by encukou** [comment]
You probably have an old `portingdb.sqlite` file lying around. Remove it and try again.

**Comment by frenzymadness** [comment]
Yes, you are right, sorry.
